version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: emby-nginx
    restart: always
    ports:
      - 9800:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/embyCache:/var/cache/nginx/emby
  emby:
    image: xinjiawei1/emby_unlockd:latest
    container_name: emby-server
    restart: unless-stopped
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=Asia/Hong_Kong
      - LANG=C.UTF-8
    volumes:
      - ./emby/config:/config
      - ./media:/media
    ports:
      - 9801:8096
    devices:
      - /dev/dri:/dev/dri
  alist:
    image: xhofe/alist:latest
    container_name: emby-alist
    restart: always
    volumes:
      - ./alist:/opt/alist/data
    ports:
      - 9802:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022